Don't make assumptions about convenience scripts' CWD.

diff --git a/__open_relation b/__open_relation
--- a/__open_relation
+++ b/__open_relation
@@ -12,8 +12,6 @@
 
 relname=$1
 
-# Spoof home director, to avoid clobbering real /.wxHexEditor file
-HOME=$(pwd)
 wxconfig="$HOME/.wxHexEditor"
 
 if ! psql --no-psqlrc -c "CHECKPOINT"
@@ -72,20 +70,20 @@ FULLPATH="$PGDATA/$RFN"
 echo "Running pg_hexedit against $FULLPATH, the first segment in relation $relname..."
 echo "Note: Only blocks $MIN_BLOCK_TAGS - $MAX_BLOCK_TAGS will be annotated, to keep overhead low"
 
-if ! ./pg_hexedit -D "$ATTRLIST" -z -R "$MIN_BLOCK_TAGS" "$MAX_BLOCK_TAGS" "$FULLPATH" > "$FULLPATH.tags"
+if ! $HOME/pg_hexedit -D "$ATTRLIST" -z -R "$MIN_BLOCK_TAGS" "$MAX_BLOCK_TAGS" "$FULLPATH" > "$FULLPATH.tags"
 then
   echo "Error encountered by pg_hexedit. Could not generate all tags."
-  echo "You may still wish to run: $HEXEDITOR $FULLPATH"
+  echo "You may still wish to run: $HOME/$HEXEDITOR $FULLPATH"
   exit 1
 fi
 
-if [ ! -f "$HEXEDITOR" ]
+if [ ! -f $(echo "$HEXEDITOR") ]
 then
-  echo "\"$HEXEDITOR\" executable not found"
+  echo "\"$HOME/$HEXEDITOR\" executable not found"
   echo "\"$FULLPATH.tags\" annotation file was still created"
   exit 1
 fi
 
-echo "Opening $FULLPATH with $HEXEDITOR..."
+echo "Opening $FULLPATH with $HOME/$HEXEDITOR..."
 # Output from wxHexEditor is verbose, and not terribly useful, so we redirect:
 $HEXEDITOR "$FULLPATH" &> /dev/null
